watch_without_answers:
	typst watch hw.typ --root ../../ --input show_answers=false --open Skim

without_answers:
	typst compile hw.typ --root ../../ --input show_answers=false

with_answers:
	typst compile hw.typ --root ../../ hw_with_answers.pdf

watch_with_answers:
	typst watch hw.typ --root ../../ hw_with_answers.pdf --open Skim
