#!/bin/sh
# Create a fresh release directory
rm -rf release
mkdir -p release

# Strip out the solutions from the code.
sed '/^ *### SOLUTION START ###/,/^ *### SOLUTION END ###/d' hw.py > release/hw.py
sed '/^ *%%% Answer START %%%/,/^ *%%% Answer END %%%/d' hw.tex > release/hw.tex

cp requirements.txt release
cp test_hw.py release
cp README.md release
